# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGNryMkmvUCj3nV_isut8rN23pfdDwbJ
"""

minimo = 900000
nombre = input("Digite su nombre: ")
apellido = input("Digite su apellido: ") 
edad = int(input("digite su edad: "))
puntaje = int(input("Ingrese el puntaje obtenido: "))
ingresos = int(input("Digite sus ingresos mensuales: "))
descuento_total = descuento1 + descuento2 + descuento3
if edad >= 0: 
    if edad > 14 and edad <= 18:
        descuento1 = (25)
    elif edad >= 19 and edad <= 21:
        descuento1 = (15)
    elif edad >=22 and edad <= 25:
        descuento1 = (10)
    else:
        descuento1 = 0
if puntaje > 0 and puntaje <= 100 :  
    if puntaje > 79 and puntaje < 86:
        descuento2 = (30)
    elif puntaje >= 86 and puntaje < 91:
        descuento2 = (35)
    elif puntaje >= 91 and puntaje < 96:
        descuento2 = (40)
    elif puntaje >= 96 :
        descuento2 = (45)
    else:
        descuento2 = 0
if ingresos >= 0 :
    if ingresos <= minimo :
        descuento3 = (30)
    elif ingresos > minimo and ingresos <= minimo * 2 :
        descuento3 = (20)
    elif ingresos > minimo * 2  and ingresos <= minimo * 3 :
        descuento3 = (10)
    elif ingresos > minimo * 3 and ingresos <= minimo * 4 :
        descuento3 = (0.5)
    else:
        descuento = 0
print(("Nombre del alumno"),str(nombre))
print(("Apellido del alumno"), str(apellido))
print(str("Apoyo por edad"),(descuento1),str("%"))
print(str("Apoyo por puntaje "),(descuento2), str("%"))
print(str("Apoyo por ingresos"),(descuento3), str("%"))
print(str("Su descuento total es de :"), descuento_total, str("%"))